# Permalinks
permalink:      /:title

# Setup
title:          Jaco Loves to Read
baseurl:        ""
url:            "https://jacolovestoread.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
